### PR TITLE
add a simple child fluent method

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by frett** [comment]
allows you to write: `dn.child("ou", "child")` instead of `dn.descendant(new Dn.Component("ou", "child"))`

**Comment by frett** [comment]
this was in the Relative DN work we aren't going to be using

**Comment by hlbraddock** [comment]
Actual use case?

**Comment by hlbraddock** [comment]
+1

**Comment by frett** [comment]
ease of building an arbitrary `Dn`, makes some logic much simpler:
https://github.com/CruGlobal/thekey/pull/34/files#diff-1206e8bc498268ed0e232594ab92bd8cR48

**Pull request merged**
