### PR TITLE
MFA Encrypted Secret attribute

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by hlbraddock** [comment]
This PR doesn't dictate, but I presume caller's will encrypt the secret?

**Comment by hlbraddock** [comment]
Are you concerned at all about code coverage % drop?

**Comment by frett** [comment]
still a work in progress :)

I'm not concerned with the coverage drop at the moment since it's just an additional attribute added.

regarding encryption of the secret, I haven't decided if I want to utilize encryption for it yet. I'm still working on getting functionality working, then I'll worry about the details of how to protect the stored secrets :)

**Comment by frett** [comment]
I do need to encrypt the secrets per the recommendation here: https://tools.ietf.org/html/rfc6238#section-5.1
> We also RECOMMEND storing the keys securely in the validation system,
   and, more specifically, encrypting them using tamper-resistant
   hardware encryption and exposing them only when required: for
   example, the key is decrypted when needed to verify an OTP value, and
   re-encrypted immediately to limit exposure in the RAM to a short
   period of time.

**Comment by frett** [comment]
I implemented MFA secret encryption in The Key right before the secret is used.
See: https://github.com/CruGlobal/thekey/pull/280

I am going to update the field to be `mfaEncryptedSecret` to indicate that it is encrypted.

**Pull request merged**
