### PR TITLE
Relative DNs

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by frett** [comment]
want to experiment with this a little bit before committing to it

**Comment by frett** [comment]
@hlbraddock thoughts on this?

it adds support for `rel = dn.relativeTo(baseDn)` and `abs = relDn.resolve(baseDn)`

**Comment by hlbraddock** [comment]
What impetus for this? My presentation layer?

**Comment by frett** [comment]
yeah, you've been doing several substrings to get a relative Dn, might as well make it an API that does it based on raw components.

**Comment by frett** [comment]
closing this since we decided not to pursue this.

**Pull request closed without merging**
